package crm.com.model;

public class ContactKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.customerid
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private Integer customerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.id
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private Integer id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.customerid
	 * @return  the value of contact.customerid
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public Integer getCustomerid() {
		return customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.customerid
	 * @param customerid  the value for contact.customerid
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setCustomerid(Integer customerid) {
		this.customerid = customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.id
	 * @return  the value of contact.id
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.id
	 * @param id  the value for contact.id
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}
}