package crm.com.model;

public class Contact extends ContactKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.name
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.position
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.tel
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.phone
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.qq
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.weixin
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String weixin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contact.email
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String email;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.name
	 * @return  the value of contact.name
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.name
	 * @param name  the value for contact.name
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.position
	 * @return  the value of contact.position
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.position
	 * @param position  the value for contact.position
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.tel
	 * @return  the value of contact.tel
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.tel
	 * @param tel  the value for contact.tel
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.phone
	 * @return  the value of contact.phone
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.phone
	 * @param phone  the value for contact.phone
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.qq
	 * @return  the value of contact.qq
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.qq
	 * @param qq  the value for contact.qq
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.weixin
	 * @return  the value of contact.weixin
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getWeixin() {
		return weixin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.weixin
	 * @param weixin  the value for contact.weixin
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setWeixin(String weixin) {
		this.weixin = weixin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contact.email
	 * @return  the value of contact.email
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contact.email
	 * @param email  the value for contact.email
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}
}