package crm.com.model;

public class Customer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.ID
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private Integer ID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.name
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.address
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.zipcode
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String zipcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.fax
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String fax;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.ID
	 * @return  the value of customer.ID
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public Integer getID() {
		return ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.ID
	 * @param ID  the value for customer.ID
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setID(Integer ID) {
		this.ID = ID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.name
	 * @return  the value of customer.name
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.name
	 * @param name  the value for customer.name
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.address
	 * @return  the value of customer.address
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.address
	 * @param address  the value for customer.address
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.zipcode
	 * @return  the value of customer.zipcode
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getZipcode() {
		return zipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.zipcode
	 * @param zipcode  the value for customer.zipcode
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.fax
	 * @return  the value of customer.fax
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.fax
	 * @param fax  the value for customer.fax
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}
}