package crm.com.model;

public class SysDept {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysdept.id
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysdept.name
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysdept.parentid
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private Integer parentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysdept.iconCls
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String iconCls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysdept.ptopid
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private Integer ptopid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysdept.pthird
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private Integer pthird;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysdept.id
	 * @return  the value of sysdept.id
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysdept.id
	 * @param id  the value for sysdept.id
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysdept.name
	 * @return  the value of sysdept.name
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysdept.name
	 * @param name  the value for sysdept.name
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysdept.parentid
	 * @return  the value of sysdept.parentid
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public Integer getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysdept.parentid
	 * @param parentid  the value for sysdept.parentid
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysdept.iconCls
	 * @return  the value of sysdept.iconCls
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getIconCls() {
		return iconCls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysdept.iconCls
	 * @param iconCls  the value for sysdept.iconCls
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setIconCls(String iconCls) {
		this.iconCls = iconCls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysdept.ptopid
	 * @return  the value of sysdept.ptopid
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public Integer getPtopid() {
		return ptopid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysdept.ptopid
	 * @param ptopid  the value for sysdept.ptopid
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setPtopid(Integer ptopid) {
		this.ptopid = ptopid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysdept.pthird
	 * @return  the value of sysdept.pthird
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public Integer getPthird() {
		return pthird;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysdept.pthird
	 * @param pthird  the value for sysdept.pthird
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setPthird(Integer pthird) {
		this.pthird = pthird;
	}
}