package crm.com.model;

public class SysUserKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysuser.id
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysuser.idcard
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String idcard;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysuser.id
	 * @return  the value of sysuser.id
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysuser.id
	 * @param id  the value for sysuser.id
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysuser.idcard
	 * @return  the value of sysuser.idcard
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getIdcard() {
		return idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysuser.idcard
	 * @param idcard  the value for sysuser.idcard
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}
}