package crm.com.model;

import java.util.Date;

public class VisitLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column visitlog.id
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column visitlog.customerid
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private Integer customerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column visitlog.idcard
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String idcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column visitlog.vdate
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private Date vdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column visitlog.vtype
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String vtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column visitlog.vremark
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	private String vremark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column visitlog.id
	 * @return  the value of visitlog.id
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column visitlog.id
	 * @param id  the value for visitlog.id
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column visitlog.customerid
	 * @return  the value of visitlog.customerid
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public Integer getCustomerid() {
		return customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column visitlog.customerid
	 * @param customerid  the value for visitlog.customerid
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setCustomerid(Integer customerid) {
		this.customerid = customerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column visitlog.idcard
	 * @return  the value of visitlog.idcard
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getIdcard() {
		return idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column visitlog.idcard
	 * @param idcard  the value for visitlog.idcard
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column visitlog.vdate
	 * @return  the value of visitlog.vdate
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public Date getVdate() {
		return vdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column visitlog.vdate
	 * @param vdate  the value for visitlog.vdate
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setVdate(Date vdate) {
		this.vdate = vdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column visitlog.vtype
	 * @return  the value of visitlog.vtype
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getVtype() {
		return vtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column visitlog.vtype
	 * @param vtype  the value for visitlog.vtype
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setVtype(String vtype) {
		this.vtype = vtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column visitlog.vremark
	 * @return  the value of visitlog.vremark
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public String getVremark() {
		return vremark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column visitlog.vremark
	 * @param vremark  the value for visitlog.vremark
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	public void setVremark(String vremark) {
		this.vremark = vremark;
	}
}