package crm.com.dao;

import crm.com.model.Contact;
import crm.com.model.ContactExample;
import crm.com.model.ContactKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContactMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contact
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int countByExample(ContactExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contact
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int deleteByExample(ContactExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contact
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int deleteByPrimaryKey(ContactKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contact
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int insert(Contact record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contact
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int insertSelective(Contact record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contact
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	List<Contact> selectByExample(ContactExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contact
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	Contact selectByPrimaryKey(ContactKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contact
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Contact record, @Param("example") ContactExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contact
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByExample(@Param("record") Contact record, @Param("example") ContactExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contact
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByPrimaryKeySelective(Contact record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contact
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByPrimaryKey(Contact record);
}