package crm.com.dao;

import crm.com.model.SysDept;
import crm.com.model.SysDeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysDeptMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysdept
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int countByExample(SysDeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysdept
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int deleteByExample(SysDeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysdept
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysdept
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int insert(SysDept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysdept
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int insertSelective(SysDept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysdept
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	List<SysDept> selectByExample(SysDeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysdept
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	SysDept selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysdept
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByExampleSelective(@Param("record") SysDept record, @Param("example") SysDeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysdept
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByExample(@Param("record") SysDept record, @Param("example") SysDeptExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysdept
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByPrimaryKeySelective(SysDept record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysdept
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByPrimaryKey(SysDept record);
}