package crm.com.dao;

import crm.com.model.SysMenu;
import crm.com.model.SysMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysMenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysmenu
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int countByExample(SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysmenu
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int deleteByExample(SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysmenu
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysmenu
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int insert(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysmenu
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int insertSelective(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysmenu
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	List<SysMenu> selectByExample(SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysmenu
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	SysMenu selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysmenu
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByExampleSelective(@Param("record") SysMenu record, @Param("example") SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysmenu
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByExample(@Param("record") SysMenu record, @Param("example") SysMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysmenu
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByPrimaryKeySelective(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysmenu
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByPrimaryKey(SysMenu record);
}