package crm.com.dao;

import crm.com.model.SysRole;
import crm.com.model.SysRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysrole
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int countByExample(SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysrole
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int deleteByExample(SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysrole
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysrole
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int insert(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysrole
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int insertSelective(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysrole
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	List<SysRole> selectByExample(SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysrole
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	SysRole selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysrole
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByExampleSelective(@Param("record") SysRole record, @Param("example") SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysrole
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByExample(@Param("record") SysRole record, @Param("example") SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysrole
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByPrimaryKeySelective(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysrole
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByPrimaryKey(SysRole record);
}