package crm.com.dao;

import crm.com.model.SysUser;
import crm.com.model.SysUserExample;
import crm.com.model.SysUserKey;
import crm.com.model.easyui.PageHelper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import crm.com.model.SysMenu;

public interface SysUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysuser
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int countByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysuser
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int deleteByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysuser
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int deleteByPrimaryKey(SysUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysuser
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int insert(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysuser
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int insertSelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysuser
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	List<SysUser> selectByExample(SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysuser
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	SysUser selectByPrimaryKey(SysUserKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysuser
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysuser
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysuser
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByPrimaryKeySelective(SysUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sysuser
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByPrimaryKey(SysUser record);

	List<SysMenu> getMenuByUserId(@Param("userId") int userId);
	
	Long getDatagridTotal(@Param("user")SysUser user,@Param("csysid")Integer sysid);

    List<SysUser> datagridUser(@Param("page")PageHelper page,@Param("csysid")Integer sysid);

}