package crm.com.dao;

import crm.com.model.VisitLog;
import crm.com.model.VisitLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VisitLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitlog
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int countByExample(VisitLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitlog
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int deleteByExample(VisitLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitlog
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitlog
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int insert(VisitLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitlog
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int insertSelective(VisitLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitlog
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	List<VisitLog> selectByExample(VisitLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitlog
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	VisitLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitlog
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByExampleSelective(@Param("record") VisitLog record, @Param("example") VisitLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitlog
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByExample(@Param("record") VisitLog record, @Param("example") VisitLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitlog
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByPrimaryKeySelective(VisitLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table visitlog
	 * @mbggenerated  Wed Aug 24 15:47:00 CST 2016
	 */
	int updateByPrimaryKey(VisitLog record);
}